Customer.Web/Models/Order/OrderListEntryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Customer.Web.Models.Order
{
    public class OrderListEntryViewModel
    {
        public Guid OrderGuid { get; set; }
        public string Status { get; set; }
        public DateTime? DateCompleted { get; set; }
        public DateTime? DatePlaced { get; set; }
        public bool IsCancelled { get; set; }

        [DataType(DataType.Currency)]
        public decimal TotalPrice { get; set; }

        public List<OrderListProductViewModel> Products { get; set; } = new List<OrderListProductViewModel>();

        public bool IsCompleted
        {
            get
            {
                return DateCompleted != null;
            }
        }
    }
}

Customer.Web/Models/Order/OrderListProductViewModel.cs
namespace Customer.Web.Models.Order
{
    public class OrderListProductViewModel
    {
        public string ProductName { get; set; }
        public int Quantity { get; set; }
    }
}

Customer.Web/Models/Order/OrdersDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Customer.Web.Models.Order
{
    public class OrderDetailsViewModel
    {
        public Guid OrderGuid { get; set; }
        public DateTime DateCompleted { get; set; }
        public DateTime DatePlaced { get; set; }

        [DataType(DataType.Currency)]
        public decimal TotalPrice { get; set; }
        public List<OrderDetailsProductViewModel> Products = new List<OrderDetailsProductViewModel>();
    }

    public class OrderDetailsProductViewModel
    {
        public string ProductName { get; set; }
        public List<string> Codes { get; set; }
        public string ImageUri { get; set; }
    }
}

Customer.Web/Controllers/OrdersController.cs
using Customer.Web.Models;
using Customer.Web.ViewModelFactories;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Web;
using System.Web.Mvc;

namespace Customer.Web.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        OrderViewModelFactory _orderViewModelFactory = new OrderViewModelFactory();

        public ActionResult OrderList()
        {
            var userGuid = GetUserGuid();

            var viewModel = _orderViewModelFactory.CreateOrderListViewModel(userGuid);
            
            return View(viewModel);
        }

        public ActionResult OrderDetails(Guid orderGuid)
        {
            var userGuid = GetUserGuid();

            var viewModel = _orderViewModelFactory.CreateOrderDetailsViewModel(orderGuid, userGuid);

            return View(viewModel);
        }

        private Guid GetUserGuid()
        {
            ApplicationUser user = System.Web.HttpContext.Current
                .GetOwinContext()
                .GetUserManager<ApplicationUserManager>()
                .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            var userGuid = user.UserId;

            return userGuid;
        }
    }
}

Customer.Web/Views/Orders/OrderDetails.cshtml
@model Customer.Web.Models.Order.OrderDetailsViewModel

<div class="row">
    <div class="row">
        <div class="col-md-3">
            Date placed: @Model.DatePlaced
            <br />
            Date completed: @Model.DateCompleted
        </div>
        <div class="col-md-6 center-text">
            @Model.OrderGuid
        </div>
        <div class="col-md-3">
            Order total value:
            <br />
            @Html.DisplayFor(m => m.TotalPrice)
        </div>
    </div>


    @foreach (var product in Model.Products)
    {
        <div class="row well well-sm">
            <div class="col-md-2">
                <a href="#" class="thumbnail">
                    @if (!string.IsNullOrWhiteSpace(product.ImageUri))
                    {
                        <img alt="@($"{ product.ProductName } -thumbnail")" src="@product.ImageUri" />
                    }
                    else
                    {
                        <img src="~/Content/Images/default_product.gif" />
                    }
                </a>
            </div>
            <div class="col-md-10">
                <h3>@product.ProductName</h3>
                <br/>
                <ul>
                    @foreach (var code in product.Codes)
                    {
                        <li>@code</li>
                    }
                </ul>
            </div>
        </div>
    }

</div>

Customer.Web/Views/Orders/OrderList.cshtml
@using Customer.Web.Models.Order

@model List<OrderListEntryViewModel>

<h3>Order list</h3>

@if (Model.Any(o => o.DateCompleted == null))
{
    <div class="alert alert-warning" role="alert">You have some unpaid orders.</div>
}

@if (Model.Any())
{
    <div class="row">
        @foreach (var order in Model)
        {
            <div class="row well well-sm">
                <div class="col-md-3">
                    <div class="col-md-12">
                        @order.DatePlaced
                    </div>
                    <div class="col-md-12">
                        @if (order.IsCompleted)
                        {
                            <span class="label label-success">COMPLETED</span>
                            <text>@order.DateCompleted</text>
                        }
                        else if (order.IsCancelled)
                        {
                            <span class="label label-danger">CANCELLED</span>
                        }
                        else
                        {
                            <span class="label label-info">Waiting for payment</span>
                        }

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-12">
                        @if (order.IsCompleted)
                        {
                            @Html.ActionLink(order.OrderGuid.ToString(), "OrderDetails", "Orders", new { orderGuid = order.OrderGuid }, null)
                        }
                        else
                        {
                            <div class="order" data-is-waiting-for-payment="@(!order.IsCancelled)" data-amount="@order.TotalPrice" data-order-guid="@order.OrderGuid.ToString()">
                                @order.OrderGuid.ToString()
                            </div>
                        }
                    </div>
                    <div class="col-md-12">
                        @foreach (var orderItem in order.Products)
                        {
                            if (orderItem.Quantity > 1)
                            {
                                @orderItem.Quantity @:x @orderItem.ProductName
                            }
                            else
                            {
                                @orderItem.ProductName
                            }
                        }
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.DisplayFor(m => order.TotalPrice)
                </div>
            </div>
        }
    </div>
}
else
{
    <p>Apparently, you dont have any orders in your history.</p>
}
